alphabates=['a','g','c','x','e','f']
alphabates[2]='k'
alphabates[2:2]=['u','t']
print(alphabates)
alphabates_extended=['g','h','j']
new_alphabet=alphabates+alphabates_extended
print(alphabates)
print(alphabates[2])
print(alphabates[-2])
print(alphabates[2:5])
print(alphabates[2:])
print(alphabates[:2])
print(alphabates[-4:])
print(alphabates[:-4])
print(alphabates[-5:-8])
print(new_alphabet)
new_alphabet.sort()
print(new_alphabet)